#!/bin/bash
#PBS -S /bin/bash

#PBS -l nodes=1:ppn=20,walltime=00:01:00 -q gigat
#PBS -N my-job-name

source ~/.bashrc
module load gcc-glibc/11
module load dealii
# ...any other modules you may need...

cd /u/par1/NMPDE-Project/build

# Create the machinefile to be passed to mpirun.
sort ${PBS_NODEFILE} | uniq -c | awk ‘{printf(“%s\n”, $2);}’ > mpd.nodes

# Actually run the simulation.
mpirun -machinefile mpd.nodes -n 20 -npernode 20 \
Project_parallel -P "jacobi" &> stdout.txt
    
